<form action="<?php echo $block->getUrl('mod8/index/save'); ?>" method="post">
    <label for="first_name">First Name:</label>
    <input type="text" name="first_name" id="first_name">
    
    <label for="last_name">Last Name:</label>
    <input type="text" name="last_name" id="last_name">
    
    <label for="email_id">Email ID:</label>
    <input type="email" name="email_id" id="email_id">
    
    <button type="submit">Save</button>
</form>
