<?php $employees = $block->getEmployees(); ?>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email ID</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($employees as $employee): ?>
            <tr>
                <td><?php echo $employee->getEmployeeId(); ?></td>
                <td><?php echo $employee->getFirstName(); ?></td>
                <td><?php echo $employee->getLastName(); ?></td>
                <td><?php echo $employee->getEmailId(); ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
